### ISSUE TITLE
Assignment 03_draft - Question(Not ready for grading)

### ISSUE THREAD

**Issue by LiMeng603** [VIS-2129-F2020/mengyao_li-vis#3]
Hi Carole, I encountered this error message when I tried to follow the tutorial to find the closest point:

At line 190,
My code is: (I am trying to find out how far each school is from a bus stop)
PUB_SCHOOL_2 <- PUB_SCHOOL %>%
mutate(bus_dist = st_nn(PUB_SCHOOL, BUS, returnDist = TRUE)$dist)

The error message is:
Problem with `mutate()` input `bus_dist`. x Query and data tables must have same dimensions i Input `bus_dist` is `st_nn(PUB_SCHOOL, BUS, returnDist = TRUE)$dist`.

I tried the st_nn function with the original dataset (lon-lat points) without transforming the coordination system, and it worked out. Yet after transformation (projected points), it failed. What exactly does the "x Query and data tables must have same dimensions" mean? Thank you!!

**Comment by c-voulgaris** [comment]
What's happening is the the locations of your bus stops are in (x,y,z) coordinates (so - three dimensions, with a z coordinate that supposedly represents elevation, but they're all set to zero, so it actually means nothing), and your school locations are in (x, y) coordinates (so, two dimensions). You can convert the bus stop locations to two dimensions (removing all the z coordinates) by adding and running the following lines before you call `st_nn()`:
```
BUS <- BUS %>%
  mutate(geometry = st_zm(geometry)) 
```
`st_zm()` removes the z coordinate form the bus stops.

**Comment by LiMeng603** [comment]
Thank you so much! It worked!
